### ISSUE TITLE
Cross Compile problem

### ISSUE THREAD

**Issue by vishnukumarts** [monkey/duda#37]
Hi,

   While compiling with cmake, i am getting the following error.  Shall i know how to get rid of this and proceed.

CMake Error at CMakeLists.txt:34 (MONKEY_PLUGIN):
Unknown CMake command "MONKEY_PLUGIN".

Thanks,

With Regards,
Vishnu Kumar T S

**Comment by fatihky** [comment]
You can take a look at #36

**Comment by vishnukumarts** [comment]
Fine I have downloaded from dst-1 branch.  But there is no configure script to generate makefile?

**Comment by edsiper** [comment]
Makefiles are generated from Makefile.in through Dudac tool, I know this way is complex for integrations so we are changing how this works entirely for the next major version (based on CMake).

**Comment by edsiper** [comment]
for the record: The error was reported against Duda dst-2 / dst-1 is the stable version.
