### ISSUE TITLE
The requested URL was not found on this server

### ISSUE THREAD

**Issue by hnkien** [monkey/duda#38]
I am running Monkey HTTP Server v1.7.0. The startup log show:
Built : Jun  6 2016 17:24:12 (/usr/lib64/ccache/cc 5.3.1)
Home  : http://monkey-project.com
[2016/06/13 09:03:38] [Warning] Listen check: consider build monkey with basic socket handling!
[2016/06/13 09:03:38] [   Info] Duda: loading service 'hello'
[+] Process ID is 4434
[+] Server listening on 0.0.0.0:80
[+] 8 threads, may handle up to 999996 client connections
[+] Loaded Plugins: liana duda 
[+] Linux Features: TCP_FASTOPEN SO_REUSEPORT 
[2016/06/13 09:03:38] [   Info] HTTP Server started

As far as I know, this already started Duda and Liana. But when running request to duda web service:
http://localhost/hello/
It prints: The requested URL was not found on this server.
I'd already configured Duda and Monkey as your guide.
How could I fix it? Thank you very much.

**Comment by edsiper** [comment]
First of all congratulations for putting the pieces together (not easy at the beginning), Monkey 1.7 and Duda dst-2 are under active development and the current state is "migrating a lot of stuff", so you may expect broken things.

To implement web services with Duda I strongly recommend you stick with the 'dst-1' branches (both on Duda and Monkey, dst-1 = duda stable v1). Just checkout dst-1 on both projects and everything should work smoothly.

note: when you get duda-examples make sure to switch to dst-1 branch too.

**Comment by hnkien** [comment]
Thank you very much.
So I have to use dst-1 for production. 
Which version of monkey is best for dst-1? Can I use dst-1 with Monkey version 1.6.9?
BR,
Kien.

**Comment by edsiper** [comment]
yeah, dst-1 is for production (that's what people use).

Monkey have a dst-1 branch, which is a 1.4 version plus several patches. Monkey >= 1.6 have a different architecture so it's not functional for Duda dst-1.

Are you missing some specific feature from Monkey 1.6 ?

**Comment by hnkien** [comment]
No, I just try Monkey 1.6 for testing performance.
Monkey 1.4 is absolutely suitable for our needs.
Eduardo Silva, thank you again for a wonderful product!
Kien.

**Comment by edsiper** [comment]
closing this issue as the answer was provided.
