### ISSUE TITLE
Server crash when sent huge data

### ISSUE THREAD

**Issue by vishnukumarts** [monkey/duda#39]
Hi,
I am using websocket chat example, if send a huge data for example more than 1000 chars, server crashes attached the core dump link.

CoreDump link:
https://www.dropbox.com/s/eghhe7rr0glai7n/core?dl=0

Thanks,

With Regards,
Vishnu Kumar T S

**Comment by edsiper** [comment]
Websocket fixes have been pushed to dst-1 branch. Please refresh your stack sources to get the fixes.

thanks for your help.

**Comment by edsiper** [comment]
Closing this issue as I cannot longer reproduce the problem after the latest fixes. If you face some anomaly please re-open.
